name: Bug Report
description: File a bug report to help us improve
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide as much detail as possible to help us resolve the issue quickly.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true
        - label: I am using a supported version of PowerShell and VMware PowerCLI
          required: true

  - type: input
    id: version
    attributes:
      label: Module Version
      description: What version of VMwareSecAssessment are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: dropdown
    id: powershell-version
    attributes:
      label: PowerShell Version
      description: What version of PowerShell are you using?
      options:
        - PowerShell 5.1
        - PowerShell 7.0
        - PowerShell 7.1
        - PowerShell 7.2
        - PowerShell 7.3
        - PowerShell 7.4
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 10
        - Windows 11
        - Windows Server 2019
        - Windows Server 2022
        - Ubuntu Linux
        - CentOS/RHEL
        - macOS
        - Other (specify in description)
    validations:
      required: true

  - type: input
    id: powercli-version
    attributes:
      label: VMware PowerCLI Version
      description: What version of VMware PowerCLI are you using?
      placeholder: "e.g., 13.1.0"
    validations:
      required: true

  - type: input
    id: vsphere-version
    attributes:
      label: vSphere Version
      description: What version of VMware vSphere are you assessing?
      placeholder: "e.g., 8.0 Update 2"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Connect to vCenter '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: Any error messages or stack traces (please format as code blocks)
      placeholder: |
        ```
        Paste error messages here
        ```

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Any relevant log entries (please format as code blocks)
      placeholder: |
        ```
        Paste log entries here
        ```

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Relevant configuration settings or custom parameters used
      placeholder: |
        ```json
        {
          "assessment": {
            "standard": "CIS",
            "scope": "Full"
          }
        }
        ```

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System unusable)
        - High (Major functionality broken)
        - Medium (Some functionality affected)
        - Low (Minor issue or cosmetic)
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Any workaround you've found for this issue
      placeholder: Describe any temporary solutions...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: environment-details
    attributes:
      label: Environment Details
      description: Please check all that apply to your environment
      options:
        - label: Air-gapped/offline environment
        - label: Large environment (>1000 VMs)
        - label: Multi-vCenter environment
        - label: Custom security policies in place
        - label: Third-party security tools installed